packer {
  required_plugins {
    veil = {
      version = ">=v0.1.0"
      source  = "github.com/jsc-masshtab/veil"
    }
  }
}

source "veil" "autogenerated_1" {
  api_token                   = "YOUR_API_TOKEN"
  api_url                   = "http://192.168.11.105"
  disk_offering             = "Small - 20GB"
  network                   = "management"
  service_offering          = "small"
  source_iso                = "CentOS-7.0-1406-x86_64-Minimal"
  ssh_username              = "root"
  template_display_text     = "Centos7-x86_64 KVM Packer"
  template_featured         = true
  template_name             = "Centos7-x86_64-KVM-Packer"
  template_os               = "Other PV (64-bit)"
  template_password_enabled = true
  template_scalable         = true
  zone                      = "NL1"
}

build {
  sources = [
    "source.veil.autogenerated_1"
  ]
}
